---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: {{ .Values.namespace }}
  name: redis-primary
spec:
  serviceName: redis-primary
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-primary
    spec:
      affinity:
       podAntiAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
         - labelSelector:
             matchExpressions:
             - key: app
               operator: In
               values:
               - redis-secondary
               - redis-primary
           topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 10
      containers:
        - name: redis-primary
          image: {{ .Values.airgapped_registry_name | default "quay.io" }}/sysdig/redis:4.0.12.1-alpine-ha
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: redis.password
#          resources:
#            limits:
#              cpu: 500m
#              memory: 100Mi
#            requests:
#              cpu: 100m
#              memory: 50Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              name: redis-primary
          volumeMounts:
            - name: redis-primary-volume
              mountPath: /data
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
      volumes:
        - name: redis-primary-volume
          emptyDir: {}
