---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: {{ .Values.namespace }}
  name: redis-sentinel
spec:
  serviceName: redis-sentinel
  replicas: 3
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - redis-sentinel
            topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-sentinel
        image: {{ .Values.airgapped_registry_name | default "quay.io" }}/sysdig/redis:4.0.12.1-alpine-ha
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 300m
            memory: 20Mi
          requests:
            cpu: 50m
            memory: 5Mi
        env:
        - name: SENTINEL
          value: redis-primary
        - name: REDIS_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: sysdigcloud-config
              key: redis.password
        ports:
        - containerPort: 26379
          name: redis-sentinel
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
