---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: {{ .Values.namespace }}
  name: sysdigcloud-cassandra
  labels:
    affinity: cassandra
    app: sysdigcloud
    role: cassandra
spec:
  updateStrategy:
    type: OnDelete
  serviceName: sysdigcloud-cassandra
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      affinity: cassandra
      app: sysdigcloud
      role: cassandra
  template:
    metadata:
      labels:
        affinity: cassandra
        app: sysdigcloud
        role: cassandra
    spec:
      ## Pod anti-affinity rules ensure that cassandra pods run on separate hosts.
      ## You may need to disable these if your number of available kubernetes hosts is less than
      ## the replication factor for your statefulset.
      affinity:
        podAntiAffinity:
          ## Strive to spread the pods across multiple AZs
          {{- if (.Values.cloudProvider.isMultiAZ | default false) }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: affinity
                      operator: In
                      values:
                        - cassandra
                topologyKey: failure-domain.beta.kubernetes.io/zone
          {{- end }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: affinity
                      operator: In
                      values:
                        - cassandra
                topologyKey: kubernetes.io/hostname
      containers:
        - image: {{ .Values.airgapped_registry_name | default "quay.io" }}/sysdig/cassandra:2.1.21.12
          name: cassandra
          env:
            - name: CASSANDRA_SERVICE
              value: sysdigcloud-cassandra
            - name: CASSANDRA_CLUSTER_NAME
              value: sysdigcloud
            - name: CASSANDRA_CLUSTER_TIME_LIMIT
              value: "5"
            # If not using CASSANDRA_SERVICE discovery, manually configure the seeds
            # - name: CASSANDRA_SEEDS
            #   value: ""
            # If using multiple directories for data, set the path list
            # - name: CASSANDRA_DATA_DIRS
            #   value: "/var/lib/cassandra/data /var/lib/cassandra/data2"
            - name: CASSANDRA_COMPACTION_THROUGHPUT
              valueFrom:
                configMapKeyRef:
                  key: cassandra.compaction.throughput
                  name: sysdigcloud-config
            - name: JVM_EXTRA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: cassandra.jvm.options
            - name: CASSANDRA_SECURE
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: cassandra.secure
            - name: CASSANDRA_SSL
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: cassandra.ssl.enabled
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            ### Start of the custom Cassandra snitch group
            # The following entries are required for the custom Cassandra snitch (see configMap)
            - name: CASSANDRA_ENDPOINT_SNITCH
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: cassandra.endpoint.snitch
            - name: CASSANDRA_SNITCH_EXTRACT_CMD
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: cassandra.snitch.extract_cmd
            - name: CASSANDRA_SNITCH_HOSTNAME_FILE
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: cassandra.snitch.hostname.file
            - name: CASSANDRA_DC
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: cassandra.datacenter.name
            ##########################################
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "nodetool drain"]
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - /ready.sh
            initialDelaySeconds: 15
            failureThreshold: 10
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /var/lib/cassandra
              name: data
            - mountPath: /opt/cassandra/cassandra-jvm-opts.json
              name: cassandra-jvm-opts
              subPath: cassandra-jvm-opts.json
            # Uncomment this when using multiple mount points for data
            # - mountPath: /var/lib/cassandra/data2
            #   name: data2
            ### Start of the custom Cassandra snitch group
            # The following entries are required for the custom Cassandra snitch (see configMap)
            # - mountPath: /host/etc/hostname
            #   readOnly: true
            #   name: host-etc-hostname
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
      ### Start of the custom Cassandra snitch group
      # The following entries are required for the custom Cassandra snitch (see configMap)
      volumes:
        - name: cassandra-jvm-opts
          configMap:
            name: cassandra-jvm-opts
      # - name: host-etc-hostname
      #   hostPath:
      #     path: /etc/hostname
