---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: {{ .Values.namespace }}
  name: sysdigcloud-elasticsearch
  labels:
    affinity: elasticsearch
    app: sysdigcloud
    component: elasticsearch
    role: elasticsearch
spec:
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      affinity: elasticsearch
      app: sysdigcloud
      component: elasticsearch
      role: elasticsearch
  serviceName: sysdigcloud-elasticsearch
  podManagementPolicy: Parallel
  # The number of replicas needs to be passed to the pods by ensuring that the value of ELASTICSEARCH_GOSSIP_NODES_NUM
  # matches the number set here.
  template:
    metadata:
      labels:
        affinity: elasticsearch
        app: sysdigcloud
        component: elasticsearch
        role: elasticsearch
    spec:
      ## Pod anti-affinity rules ensure that elasticsearch pods run on separate hosts.
      ## You may need to disable these if your number of available kubernetes hosts is less than
      ## the replication factor for your statefulset.
      affinity:
        podAntiAffinity:
          ## Strive to spread the pods across multiple AZs
          {{- if (.Values.cloudProvider.isMultiAZ | default false) }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: affinity
                      operator: In
                      values:
                        - elasticsearch
                topologyKey: failure-domain.beta.kubernetes.io/zone
          {{- end }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: affinity
                      operator: In
                      values:
                        - elasticsearch
                topologyKey: kubernetes.io/hostname
      containers:
        - name: elasticsearch
          image: {{ .Values.airgapped_registry_name | default "quay.io" }}/sysdig/elasticsearch:5.6.16.2
          securityContext:
            privileged: true
          envFrom:
          - configMapRef:
              name: elasticsearch
          - secretRef:
              name: elasticsearch-searchguard
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - /readiness_probe.sh
            initialDelaySeconds: 20
            timeoutSeconds: 5
            failureThreshold: 10
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data
            - mountPath: /tmp/elasticsearch-certs/
              name: elasticsearch-certs
            - mountPath: /tmp/sgconfig/
              name: sg-config
      volumes:
        - name: elasticsearch-certs
          secret:
            secretName: ca-certs
            defaultMode: 256
        - name: sg-config
          secret:
            secretName: elasticsearch-searchguard-config-files
            defaultMode: 256
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
